### ISSUE TITLE
How does `degit` differ from a shallow clone?

### ISSUE THREAD

**Issue by kzc** [Rich-Harris/degit#10]
> much quicker than using git clone, because you're not downloading the entire git history.

How does `degit` differ from a shallow clone?

* https://git-scm.com/docs/git-clone#git-clone---depthltdepthgt
* https://www.perforce.com/blog/git-beyond-basics-using-shallow-clones

Might be worth mentioning in the README.

**Comment by Rich-Harris** [comment]
thanks, have moved my response to https://github.com/Rich-Harris/degit/issues/7 into the README
