### ISSUE TITLE
Should use https to get refs, not ssh

### ISSUE THREAD

**Issue by melniker** [Rich-Harris/degit#11]
By using ssh protocol for the getRefs function, the user is forced to set up ssh keys in GitHub, if s/he doesn't already have it set up. Seems unnecessary, since the .tar.gz pull is explicitly via HTTP protocol. 

Let me know if I'm totally off base (git noob / github contributor noob ... just trying to help :))!

**Comment by Rich-Harris** [comment]
Thank you! This makes total sense. Have released it as 1.1.0 🎉
