### ISSUE TITLE
Slightly confusing readme

### ISSUE THREAD

**Issue by SteveALee** [Rich-Harris/degit#156]
The 1st paragraph in the README says

"and download the associated tar file to ~/.degit/some-user/some-repo/commithash.tar.gz if it doesn't already exist locally"

but the behaviour I see is a bunch of local files, not the zip as this implies

**Comment by Rich-Harris** [comment]
If you look at the `~/.degit` folder, you'll see `.tar.gz` files, not their contents. The contents of your project folder are created *from* those zip files
