### ISSUE TITLE
requires node 8?

### ISSUE THREAD

**Issue by kzc** [Rich-Harris/degit#17]
I was unable to install or run this tool without node 8 due to use of `async`:

https://github.com/Rich-Harris/degit/blob/84b215cfd9aa8d1a040c3fb30e6609700886a4e4/bin/index.js#L36

Shouldn't `engine` should be specified in `package.json`?

**Comment by Rich-Harris** [comment]
Good catch, thanks — released 1.2.1 with @TehShrike's fix, and an update to the README
