### ISSUE TITLE
[FR] use HEAD as default branch

### ISSUE THREAD

**Issue by Cologler** [Rich-Harris/degit#170]
Some repo does not have the master branch (like https://github.com/npm/hosted-git-info).

![image](https://user-images.githubusercontent.com/10906962/74858904-05b73200-5381-11ea-814f-82c20629e64c.png)

**Comment by keerthivasan-r** [comment]
HEAD is just a pointer, not really a branch. It points to the latest commit that you performed in the branch you are on. you can run

`git branch --show-current` 

to get the current branch you are

**Comment by Cologler** [comment]
> It points to the latest commit that you performed in the branch you are on. you can run

Yeah, and my image showed how to get the real branch from the HEAD.

**Comment by keerthivasan-r** [comment]
oh, ok. so, you want to get the commit of HEAD and get the branch by comparing the commits. Is that right?

**Comment by Cologler** [comment]
> oh, ok. so, you want to get the commit of HEAD and get the branch by comparing the commits. Is that right?

Yes.

**Comment by keerthivasan-r** [comment]
I understand now, thank you!

**Comment by keerthivasan-r** [comment]
I think this can get the default branch of git repository. What do you think

`git symbolic-ref --short HEAD`

**Comment by Cologler** [comment]
> I think this can get the default branch of git repository. What do you think
> 
> `git symbolic-ref --short HEAD`

`symbolic-ref` seems unable to load from remote repo.

**Comment by keerthivasan-r** [comment]
Yeah, you are right. How do you think about this one? It seems to bring only default branch in the repository

`git clone --single-branch https://github.com/npm/hosted-git-info.git`

**Comment by keerthivasan-r** [comment]
There is a default hard code value `master`. I think that is the problem. we will have to figure out the default branch by HEAD ref hash on the fly.

```
        const user = match[4];
	const name = match[5].replace(/\.git$/, '');
	const subdir = match[6];
	const ref = match[7] || 'master';
```

Does that right?

**Comment by Cologler** [comment]
Yes, this is probably what I want.

**Comment by keerthivasan-r** [comment]
Great, thanks. I will be glad to give a PR.

**Comment by keerthivasan-r** [comment]
@Cologler Please review #204

**Comment by Cologler** [comment]
LGTM.
