### ISSUE TITLE
Support private repos

### ISSUE THREAD

**Issue by Rich-Harris** [Rich-Harris/degit#2]
Haven't looked into what this would entail

**Comment by vutran** [comment]
I would imagine something simple like this would work:

```
degit some/repo --token abc123
```

**Comment by Rich-Harris** [comment]
That could work, yeah. Would be nice if it used your existing keychain (for HTTPS) or SSH keys as well, just like `git clone` does.

**Comment by Andarist** [comment]
> Would be nice if it used your existing keychain (for HTTPS) or SSH keys as well, just like git clone does.

Played with a it a little bit, but cannot figure out how to reuse existing keychain. Does anyone have any pointers?

**Comment by hipstersmoothie** [comment]
> Would be nice if it used your existing keychain

This would be awesome. I want to use degit to clone repos on our enterprise github and it get stuck doing the fetch because our enterprise github redirects to a login. The other git command work because they use the keychain

**Comment by YogliB** [comment]
Closed via #29.
