### ISSUE TITLE
setting a different default branch

### ISSUE THREAD

**Issue by hamilton** [Rich-Harris/degit#207]
Hi Rich! Many of the code bases I work on w/ others are renaming `master` to `main`. Is there an easy way to set the default branch w/ `degit` to something that isn't `master` within a project?

**Comment by korakot** [comment]
I face the same problem.

Please have `degit` check for both `master` and `main` as defaults.

**Comment by canadaduane** [comment]
I'm having the same issue. Is there a workaround for now?
