### ISSUE TITLE
[!] could not find commit hash for master

### ISSUE THREAD

**Issue by rob-balfre** [Rich-Harris/degit#22]
Was trying out degit and got this error...

node v8.4.0
degit v1.2.2
osx  v10.12.4

```bash
npm install -g degit
degit svelte/template
```

Error: [!] could not find commit hash for master

**Comment by Rich-Harris** [comment]
It should be `sveltejs/template`, not `svelte/template`. Hmm, we probably need a better error...

**Comment by rob-balfre** [comment]
ah stupid me!  Yeah I guess the error could be more helpful.  Thanks.
