### ISSUE TITLE
Error when attempting to use

### ISSUE THREAD

**Issue by jacwright** [Rich-Harris/degit#24]
Getting the following error when attempting to use degit (even trying `degit -h`):

```
.../lib/node_modules/degit/index.js:89
	async clone(dest) {
	      ^^^^^

SyntaxError: Unexpected identifier
```

Is this supposed to be compiled? Or is node 6 not supported?
Node v6.11.3 npm v3.10.10

**Comment by TehShrike** [comment]
Node 6 is not supported: https://github.com/Rich-Harris/degit/blob/cf987d3503988dd29445d2e728cae83a345f8387/package.json#L5
