### ISSUE TITLE
npx degit sveltejs/template my_app not working

### ISSUE THREAD

**Issue by salmanelalhi** [Rich-Harris/degit#244]
This is the log:

0 verbose cli [
0 verbose cli   'C:\\Program Files\\nodejs\\node.exe',
0 verbose cli   'C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js',
0 verbose cli   'exec',
0 verbose cli   '--',
0 verbose cli   'degit',
0 verbose cli   'sveltejs/template',
0 verbose cli   'my_app'
0 verbose cli ]
1 info using npm@7.0.8
2 info using node@v15.2.1
3 timing config:load:defaults Completed in 1ms
4 timing config:load:file:C:\Program Files\nodejs\node_modules\npm\npmrc Completed in 1ms
5 timing config:load:builtin Completed in 1ms
6 timing config:load:cli Completed in 1ms
7 timing config:load:env Completed in 1ms
8 timing config:load:file:C:\Users\selahi\workspace\Sveltespace\.npmrc Completed in 0ms
9 timing config:load:project Completed in 1ms
10 timing config:load:file:C:\Users\selahi\.npmrc Completed in 0ms
11 timing config:load:user Completed in 0ms
12 timing config:load:file:C:\Users\selahi\AppData\Roaming\npm\etc\npmrc Completed in 0ms
13 timing config:load:global Completed in 0ms
14 timing config:load:cafile Completed in 1ms
15 timing config:load:validate Completed in 0ms
16 timing config:load:setUserAgent Completed in 0ms
17 timing config:load:setEnvs Completed in 1ms
18 timing config:load Completed in 7ms
19 verbose npm-session 2b0b0dbcd06a99d3
20 timing npm:load Completed in 13ms
21 http fetch GET 304 https://registry.npmjs.org/degit 138ms (from cache)
22 timing arborist:ctor Completed in 0ms
23 timing arborist:ctor Completed in 0ms
24 timing arborist:ctor Completed in 0ms
25 timing command:exec Completed in 288ms
26 verbose stack Error: command failed
26 verbose stack     at ChildProcess.<anonymous> (C:\Program Files\nodejs\node_modules\npm\node_modules\@npmcli\promise-spawn\index.js:64:27)
26 verbose stack     at ChildProcess.emit (node:events:329:20)
26 verbose stack     at maybeClose (node:internal/child_process:1055:16)
26 verbose stack     at Process.ChildProcess._handle.onexit (node:internal/child_process:288:5)
27 verbose cwd C:\Users\selahi\workspace\Sveltespace
28 verbose Windows_NT 10.0.18363
29 verbose argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "exec" "--" "degit" "sveltejs/template" "my_app"
30 verbose node v15.2.1
31 verbose npm  v7.0.8
32 error code 1
33 error path C:\Users\selahi\workspace\Sveltespace
34 error command failed
35 error command C:\windows\system32\cmd.exe /d /s /c ""degit" "sveltejs\template" "my_app""
36 verbose exit 1

---------------
Terminal output:

C:\Users\selahi\AppData\Local\npm-cache\_npx\ca8ac1ce5606ff91\node_modules\degit\dist\index-26d8486e.js:15111
                throw new DegitError(`could not parse ${src}`, {
                      ^

DegitError: could not parse sveltejs\template
    at parse$4 (C:\Users\selahi\AppData\Local\npm-cache\_npx\ca8ac1ce5606ff91\node_modules\degit\dist\index-26d8486e.js:15111:9)
    at new Degit (C:\Users\selahi\AppData\Local\npm-cache\_npx\ca8ac1ce5606ff91\node_modules\degit\dist\index-26d8486e.js:14817:15)
    at Object.degit (C:\Users\selahi\AppData\Local\npm-cache\_npx\ca8ac1ce5606ff91\node_modules\degit\dist\index-26d8486e.js:14804:9)
    at run (C:\Users\selahi\AppData\Local\npm-cache\_npx\ca8ac1ce5606ff91\node_modules\degit\dist\bin.js:5609:18)
    at main (C:\Users\selahi\AppData\Local\npm-cache\_npx\ca8ac1ce5606ff91\node_modules\degit\dist\bin.js:5604:3)
    at Object.<anonymous> (C:\Users\selahi\AppData\Local\npm-cache\_npx\ca8ac1ce5606ff91\node_modules\degit\dist\bin.js:5627:1)
    at Module._compile (node:internal/modules/cjs/loader:1102:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1131:10)
    at Module.load (node:internal/modules/cjs/loader:967:32)
    at Function.Module._load (node:internal/modules/cjs/loader:807:14) {
  code: 'BAD_SRC'
}

Any help please?

Thanks

**Comment by mducharm** [comment]
I got this same issue today - specifically the `DegitError: could not parse sveltejs\template`. Although it's not as convenient, as a temporary work around I just cloned the repo, deleted .git/ and reinitialized with `git init`.

**Comment by waldganger** [comment]
Same issue here on windows 10 20H2 and node v14.15.1.

**Comment by waldganger** [comment]
> Same issue here on windows 10 20H2 and node v14.15.1.

Sorry I found the problem. Node is installed in my c:\Programs folder. But I had an ancient npm and npm-cache folders in my $USER\AppData\Roaming folder. I deleted those and now everything works.

**Comment by hoishing** [comment]
I got the same issue, and found that it is caused by missing npm itself in the global scope. So it can be solved by:
`npm install npm -g`

**Comment by fyradir** [comment]
Got the same behavior. `npx degit sveltejs/template xxxx` fails gloriously. Deleted my entire NPM cache before re-running the command.

```
C:\Users\Omniboy>npx degit sveltejs/template svelte-test
npm notice
npm notice New minor version of npm available! 7.0.15 -> 7.3.0
npm notice Changelog: https://github.com/npm/cli/releases/tag/v7.3.0
npm notice Run npm install -g npm@7.3.0 to update!
npm notice
C:\Users\Omniboy\AppData\Roaming\npm\node_modules\degit\dist\index-26d8486e.js:15111
                throw new DegitError(`could not parse ${src}`, {
                      ^

DegitError: could not parse sveltejs\template
    at parse$4 (C:\Users\Omniboy\AppData\Roaming\npm\node_modules\degit\dist\index-26d8486e.js:15111:9)
    at new Degit (C:\Users\Omniboy\AppData\Roaming\npm\node_modules\degit\dist\index-26d8486e.js:14817:15)
    at Object.degit (C:\Users\Omniboy\AppData\Roaming\npm\node_modules\degit\dist\index-26d8486e.js:14804:9)
    at run (C:\Users\Omniboy\AppData\Roaming\npm\node_modules\degit\dist\bin.js:5609:18)
    at main (C:\Users\Omniboy\AppData\Roaming\npm\node_modules\degit\dist\bin.js:5604:3)
    at Object.<anonymous> (C:\Users\Omniboy\AppData\Roaming\npm\node_modules\degit\dist\bin.js:5627:1)
    at Module._compile (node:internal/modules/cjs/loader:1108:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1137:10)
    at Module.load (node:internal/modules/cjs/loader:973:32)
    at Function.Module._load (node:internal/modules/cjs/loader:813:14) {
  code: 'BAD_SRC'
}
npm ERR! code 1
npm ERR! path C:\Users\Omniboy
npm ERR! command failed
npm ERR! command C:\WINDOWS\system32\cmd.exe /d /s /c degit sveltejs\template svelte-test

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\Omniboy\AppData\Local\npm-cache\_logs\2020-12-23T21_51_57_433Z-debug.log
```

**Comment by hoishing** [comment]
@fyradir do you have npm installed in global scope? ie. does npm show up in `npm list -g` ? If not, `npm i npm@7.3.0 -g` may work around this, though I think degit should be able to use the system-wide npm. ie. `C:\Program Files\nodejs\npm` in Windows.

**Comment by fyradir** [comment]
@hoishing 
```
C:\Users\Omniboy>npm list -g
C:\Users\Omniboy\AppData\Roaming\npm
+-- degit@2.8.0
+-- npm@
+-- npx@10.2.2
`-- serve@11.3.2
```

**Comment by hoishing** [comment]
@fyradir its a bit strange that you don't have a version number for npm. How about upgrade it with `npm i npm@7.3.0 -g` ?

**Comment by fyradir** [comment]
@hoishing 
```
C:\Users\Omniboy>npm i npm@7.3.0 -g
npm ERR! code EEXIST
npm ERR! path C:\Users\Omniboy\AppData\Roaming\npm\npx.ps1
npm ERR! EEXIST: file already exists
npm ERR! File exists: C:\Users\Omniboy\AppData\Roaming\npm\npx.ps1
npm ERR! Remove the existing file and try again, or run npm
npm ERR! with --force to overwrite files recklessly.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\Omniboy\AppData\Local\npm-cache\_logs\2020-12-24T13_52_38_860Z-debug.log
```

**Comment by hoishing** [comment]
I suspect the the issue is caused by degit not able to locate npm in Windows. After installing npm in global scope, it can.

**Comment by RiskTolerance** [comment]
Installing in the global scope fixed it for me! Thanks @hoishing!

**Comment by salmanelalhi** [comment]
Sorry for late acknowledgement, installing in the global space fixed it for me too! Thanks @hoishing
