### ISSUE TITLE
Github now has default branch as "main", update behaviour to accomodate?

### ISSUE THREAD

**Issue by EriKWDev** [Rich-Harris/degit#254]
There are more and more GitHub repos whose main branch is called "main" and no-longer "master". Would it perhaps be possible to either a) change the default branch for GitHub-commands to be "main" or b) first try and get master, and, if that fails, instead try and fetch branch main and only after that fail the command.

The current error message we get is `! could not find commit hash for master`. The new message could perhaps turn into `! could not find commit hash for neither master nor main`.

**Comment by SwiftWinds** [comment]
As we wait for a response by the maintainers, consider this workaround: https://github.com/Rich-Harris/degit/issues/207#issuecomment-708409213

**Comment by fregante** [comment]
You can use a more up-to-date fork of the tool. This is abandoned.

https://github.com/tiged/tiged
