### ISSUE TITLE
Allow use of proxy settings?

### ISSUE THREAD

**Issue by poshaughnessy** [Rich-Harris/degit#26]
Hi Rich. I'm following the [Sapper Getting Started Guide](https://sapper.svelte.technology/guide#getting-started) and running: `degit sveltejs/sapper-template my-app`.

But I'm here on the office network behind a proxy - and the command hangs and eventually says "could not download".

I have my proxy settings set OK in my environment variables (`http_proxy`, `https_proxy`). I've checked that in the same terminal, I'm able to download the same URL OK using `wget`.

Would you be OK with adding the ability to deal with proxies?

I've previously done this using something like this:

```
import httpsProxyAgent from 'https-proxy-agent';

const httpsProxy = process.env.https_proxy;
let fetchOptions = null;

if (httpsProxy) {
    // Log: 'Using proxy server': httpsProxy
    fetchOptions = {agent: new httpsProxyAgent(httpsProxy)};
}

fetch(fooBarURL, fetchOptions)
```
If you'd be happy with the same approach - using [https-proxy-agent](https://www.npmjs.com/package/https-proxy-agent)? - I could write a PR if you like?

**Comment by Rich-Harris** [comment]
Yes please, a PR would be great! Thank you

**Comment by Rich-Harris** [comment]
Long overdue, but I've finally merged #27 and released 2.3.0. Thanks!

**Comment by poshaughnessy** [comment]
Cool, cheers Rich! @YogliB sorry I missed your comment on the PR from ages ago!

**Comment by dainiel** [comment]
When will  2.3.0 be released? Don't tell me it is 2022.
