### ISSUE TITLE
This link is not downloading.

### ISSUE THREAD

**Issue by Quraian** [Rich-Harris/degit#330]
This URL is not being downloaded:
https://github.com/dotnet/AspNetCore.Docs/tree/main/aspnetcore/test/integration-tests/samples/3.x/IntegrationTestsSample

No errors or anything, just empty folder.

When I try this:
https://github.com/dotnet/AspNetCore.Docs/
It works!

I'm on Windows 10.

Thanks Rich for the utility btw :)

**Comment by nake89** [comment]
Hello,

I think you are using degit slightly incorrectly. The documentation describes usage as:
`degit user/repo/subdirectory`

I tested this way and it runs successfully. I hope this helped. :)
```
➜  tmp npx degit dotnet/AspNetCore.Docs/aspnetcore/test/integration-tests/samples/3.x/IntegrationTestsSample asd
> cloned dotnet/AspNetCore.Docs#HEAD to asd
➜  tmp ls -la asd
total 0
drwxrwxr-x  4 kivi.local  staff  128 Sep 22 09:58 .
drwxr-xr-x  7 kivi.local  staff  224 Sep 22 09:58 ..
drwxrwxr-x  3 kivi.local  staff   96 Sep 22 09:58 src
drwxrwxr-x  3 kivi.local  staff   96 Sep 22 09:58 tests
➜  tmp
```

**Comment by Quraian** [comment]
@nake89 You are right 🤦‍♂️🤦‍♂️🤦‍♂️

Thank you!
