### ISSUE TITLE
Monorepos?

### ISSUE THREAD

**Issue by SupremeTechnopriest** [Rich-Harris/degit#48]
Hey Rich, 

Was wondering if theres any way to make degit work with a lerna monorepo (say a collection of templates) without some crazy action logic being implemented. Something like `degit rich-harris/monorepo/packages/template`. Thanks!

**Comment by wesleygrimes** [comment]
+1 to this, we need this capability. Might submit a PR for it.

**Comment by rainbyte** [comment]
I have made a PR to solve this issue, please review

**Comment by Rich-Harris** [comment]
Released 2.4.0 with @rainbyte's PR — thanks
